name: listiify
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_custom_clippers: ^1.1.1
  animated_text_kit: ^1.3.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  fonts:
    - family: Square Sans Serif
      fonts:
        - asset: fonts/square_sans_serif.ttf

    - family: Red Rose
      fonts:
        - asset: fonts/RedRose-Regular.ttf
